### ISSUE TITLE
Ucomen App?

### ISSUE THREAD

**Issue by Bogdis** [milo526/homebridge-tuya-web#116]
Hello,

Can anyone help me im trying to set this up but it seams that it will not work with ucomen app.
[TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error! (pass and user are correct)
I dont want to set everything up again with smart life or tuya life.

thanks

**Comment by milo526** [comment]
Hello,
I sadly have bad news for you.
The UComen app is not supported and will not be supported.
This is not something I control.

Tuya does not allow you to log in with this app on the API that this plugin is using, since I am not affiliated with Tuya, there is nothing I can do.

You options are to switch to another app (which you said you didn't want to do) or switch to another Tuya Homebridge plugin.
