### ISSUE TITLE
Motion PIR Device support

### ISSUE THREAD

**Issue by eldrix-4** [milo526/homebridge-tuya-web#117]
I’d love to see support for motion detection devices connected to the SmartLife world showing up at HomeKit devices in Homebridge. I have a zigbee hub connected to SmartLife, with a number of zigbee motion sensors connected to that, so happy to help test if that’s helpful.

**Comment by milo526** [comment]
Hello,
I understand your desires herein however I am not able to do this.

Zigbee devices (through a hub) are not supported by the API that this plugin is using.

This is a limitation imposed by Tuya, since I am not affiliated to them, there is nothing I can do to change this.

You might wanna try @iRayanKhan his plugin [homebridge-tuya](https://github.com/iRayanKhan/homebridge-tuya#readme) it's harder to setup but does support more devices.

**Comment by iRayanKhan** [comment]
Thanks for the shout! 

Motion/Contact sensors have been tricky since they don't act like "normal" Tuya devices in terms of reporting the state. Looking to fix this issue one day, but it's a device limitation.

**Comment by eldrix-4** [comment]
Thanks, I'll continue to tinker. While I can do what I need by setting up automations on the SmartLife side, it would be super nice to be have access to those sensors in Homebridge. Let me know if I can help with any testing if the time comes.

**Comment by sspencer10** [comment]
What about PIR devices not connected to a hub?
