### ISSUE TITLE
Tuya (Dual) Switch, Power Consumption Reporting

### ISSUE THREAD

**Issue by arrmo** [milo526/homebridge-tuya-web#118]
First off, I want to say thanks! Really appreciate this Homebridge plug in, and it's working well for me - so thinking this is an extension (new feature), not a bug. But I may be wrong - it has happened before ... LOL!

My Tuya switch does get integrated in to Homebridge, and I can turn it on and off. However, as it also includes power / energy monitoring functionality, it would be nice to include that. And/or make it accessible to other access (API of sorts, or save the latest readings to a file?). Just a thought.

Now, this all said, I have been digging some, and I am a bit confused by the Tuya API - is it the case that on/off can be controlled without a key, but energy monitoring requires a key? If so, I can see this being more difficult here - but again, I'm confused by Tuya cloud vs. local, key vs. no key. Any pointers / links you have on this would be appreciated!

Does this rambling sort of make sense? The bottom line - having the ability to check power (and voltage, current) for a switch would be great. I can also provide some output that I have been able to collect via tuya cli, if that helps.

Again, thanks!

**Comment by milo526** [comment]
Hey,

Thanks for the compliment and thanks for the interest.

Power monitoring won't work for this plugin due to [the api used by this plugin](https://github.com/PaulAnnekov/tuyaha).

This plugin uses a special API exposed by Tuya, it was originally meant for Home Assistant.

There is also the [homebridge-tuya](https://github.com/iRayanKhan/homebridge-tuya#readme) package by @iRayanKhan that plugin uses the local-key method. This has some connectivity to the Tuya-cli you mentioned.

Furthermore there is also the "official" tuya cloud. It would be awesome to get a homebridge plugin based on that, however it will cost the developer at least 300 dollar per year to maintain (due to tuya licensing fees). As far as I am aware, nobody has implemented this into a homebridge plugin.

If these metrics are really important to you, you might want to look into the aforementioned homebridge-tuya plugin. That might be able to support your use case or it might have the ability to be extended upon to support them.

**Comment by arrmo** [comment]
Will dig into these, thanks so much for providing some places to look - appreciate it! And I had stumbled across Home Assistant, wasn't sure how it all fit together. This does help though.

And I agree with you, I did see the Tuya cloud, and it seemed to be an expensive path 😞. I assume you are accessing the devices directly / locally, correct?

Thanks again.
