### ISSUE TITLE
problem with Tuya led stip

### ISSUE THREAD

**Issue by galoiring** [milo526/homebridge-tuya-web#186]
after install everything I have a problem with the plugin (uses smart home app) 
attached here the logs
<img width="1280" alt="צילום מסך 2021-01-31 ב-16 31 27" src="https://user-images.githubusercontent.com/74841666/106389142-9815e180-63ea-11eb-9a90-8e6da86875d5.png">
<img width="1280" alt="צילום מסך 2021-01-31 ב-16 24 29" src="https://user-images.githubusercontent.com/74841666/106389145-99470e80-63ea-11eb-82bb-124912856d45.png">

![IMG_3105](https://user-images.githubusercontent.com/74841666/106389181-bbd92780-63ea-11eb-9c3c-9338bc564bd3.jpg)

**Comment by milo526** [comment]
Sadly your specific device does not support changing brightness through the API that this plugin is using.
The API that this plugin is using is different from the one that the Tuya/Smart Life apps are using.

Since I do not work for Tuya I cannot change their API. If brightness support is important to you, consider switching to another homebrige tuya plugin.
