### ISSUE TITLE
Everything works exept fan

### ISSUE THREAD

**Issue by Final-Hawk** [milo526/homebridge-tuya-web#20]
No errors in config, it seems to have no clue that it is there. smartlife app. Any ideas?

**Comment by milo526** [comment]
Hello,

I'm sorry to hear that. Could you please follow [these steps](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device) to see if your device is supported? (and if it is place the output here). Furthermore could you maybe run you homebridge in debug mode and post the relevant output here (maybe through a gist).

**Comment by Final-Hawk** [comment]
Gees i'm sorry i did not see that part in the read me. It seems that it is not supported so i have emailed tuya. Thanks for the quick reply though

In case you are curious this is the fan. (it can go for 50$AU. So somewhat cheap for a smart fan)
http://www.goldair.com.au/product-catalogue/cooling/pedestal-fans/gcpf315

**Comment by milo526** [comment]
Hmm looking at that it seems like it could actually be supported. Did you add the fan to the Tuya app instead of the Goldair app? The setup instructions should be the same and then it should work.

Could you add the fan to the Tuya app and run the check I linked above again? Please make sure to set `BIZ_TYPE=tuya`

**Comment by Final-Hawk** [comment]
Yes i added it to the smart life app. it did not appear in the list of accessorises
