### ISSUE TITLE
Error retrieving devices states 

### ISSUE THREAD

**Issue by azmurph** [milo526/homebridge-tuya-web#24]
[TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined

I keep getting color issues when controlling from komekit.  Not sure if this is a bug or light bulbs aren’t supported. Thanks.

**Comment by milo526** [comment]
When you created this issue you should have come across a page where you could select that you wanted to create a bug report. Using that format would have helped me a lot since I would have all and if not way more of the information that I need to solve this issue.
This issue might be solved in the pre-release [v0.3.4-0](https://github.com/milo526/homebridge-tuya-web/releases/tag/v0.3.4-0). If it is not solved there please open a new issue following the bug report template.

**Comment by azmurph** [comment]
Thank you so much. I will do that. i appreciate all 
you’re doing!  
Mark Murphy
