### ISSUE TITLE
AC device settings 

### ISSUE THREAD

**Issue by BLLiNNK** [milo526/homebridge-tuya-web#285]
Could you add support for AC devices in the device settings?

**Comment by milo526** [comment]
I don't get what you are asking.

Do you want to get support for a new device? If so please follow the steps as outlined in the readme.

If you wanted to get a new device overwrite, I don't think this will happen (for this specific device type at least) since Tuya simply does not provide the information needed to relay to HomeKit (but this could be validated with the info that is requested in the issue template)
