### ISSUE TITLE
Two npm packages for this plugin.

### ISSUE THREAD

**Issue by charlesomer** [milo526/homebridge-tuya-web#37]
**Describe the bug**
This plugin appears twice in npm which effects homebridge-config-ui-x since it also appears twice there which is confusing.

**To Reproduce**
Search for "tuya web" in homebridge-config-ui-x and identify the two identical packages, one by @milo526 and the other by @basdelfos.

**Expected behavior**
One one npm packages for the same plugin.

**Additional context**
https://www.npmjs.com/package/homebridge-tuya-web
https://www.npmjs.com/package/@milo526/homebridge-tuya-web

Should be using https://www.npmjs.com/package/homebridge-tuya-web exclusively.

**Comment by milo526** [comment]
I'm planning on deprecating the non-namespaced variant once I'm happy with the namespaced variant.

This is no bug with the library and can easily be prevented by just installing one of them.

Both of the packages should be using the same code. Using both of the packages at them same time is actively discouraged since they might slightly interfere (ie they share their caches).

**Comment by charlesomer** [comment]
Okay great. I'm glad you're aware of it and it's being depreciated.
