### ISSUE TITLE
Context changes (e.g. switch off -> on) made outside of HomeKit are not reflected on the Home app GUI

### ISSUE THREAD

**Issue by cbf02000** [milo526/homebridge-tuya-web#381]
I just updated to v1.1, and noticed that context changes (e.g. switch off -> on) made outside of HomeKit are not reflected on the Home app GUI.

For example, if I turn on a switch on the Smart Life app, or on the wall switch directly, that isn't getting reflected on the HomeApp.
Note that any changes made on the Home app work just fine, and the GUI is updated.

I am fairly certain this is new as of v1.1, I tried tweaking the polling interval, but to no avail...

Is there any other switch to make sure Home.app reflects the accurate state of accessories?

**Comment by milo526** [comment]
Have you waited long enough? Updates can take up to 5 minutes to reflect any changes made outside of the homekit system.
There is no new switch that changes this behaviour.

**Comment by avielc** [comment]
Happens to me too. 
only I noticed it happening when turning on the switch (boiler) via HomeKit  it doesn’t actually reflect in the app. 

I made a few changes since the.  And now it doesn’t seem like the plug-in wants to register my devices. Any ideas why? (I tried using the official one. But it just doesn’t want to run. Issue with access token. 
many chance tuya made some change which made rendered all the plugins invalid?

**Comment by gjeida** [comment]
I am having the same behaviour as this with a switch module with local control. 

Interested in the 5min wait time you suggested, is this even after you set the polling interval to something less than the default? 

Out of interest I changed mine to 20 seconds and the status still does not get across to homekit in a timely manner, so what does the polling interval actually change, or is there a minimum polling interval burned in?

Thanks

**Comment by avielc** [comment]
In my case, apparently a restart to the router solved the issue
(embarrassing, I know)

**Comment by gjeida** [comment]
I have only just installed a tuya switch module with local 240v switch control and also a RF433 remote switch. The status only seems to change if you wait some time then view the room in homekit and the status might have updated. 
My main question is in the polling interval for the status, it does update but seemingly random (or within a certain window of time I can't confirm).
I do get an error now on restart _"[TuyaWebPlatform] Requesting too quickly. - you can discovery once in 900 seconds"_ which indicates to me that there is a 15min window somewhere, but I didn't think the changing of the polling interval was for discovery and not switch state.

**Comment by milo526** [comment]
There is a hardcoded minimum at 5 minutes, since this is a requirement from Tuya. 
 If you poll faster than every 5 minutes (it's actually just over 5 minutes, added a few seconds to account for random delays and rounding errors) you will just get errors.
For the discovery, you probably restarted the plugin within 15 minutes of the previous restart/discovery.

**Comment by gjeida** [comment]
> There is a hardcoded minimum at 5 minutes, since this is a requirement from Tuya. If you poll faster than every 5 minutes (it's actually just over 5 minutes, added a few seconds to account for random delays and rounding errors) you will just get errors. For the discovery, you probably restarted the plugin within 15 minutes of the previous restart/discovery.

OK, thanks, that clarifies it for me, might be good idea to add this information as a comment on the polling parameter definition to stop people like me asking these silly questions :-)
