### ISSUE TITLE
[Accessory Request] Garage Door Opener 

### ISSUE THREAD

**Issue by chyqichyqi** [milo526/homebridge-tuya-web#45]
Pretty new to all of this. Garage opener shows up as an outlet :( Hoping there's a way to configure this correctly. Thanks!

**Comment by milo526** [comment]
Sorry for not responding earlier, for some reason this issue was no longer on my ToDo list 🙈 

Could you please follow the steps outlined in ["How to check whether the API this library uses can control your device?"](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device).

**Comment by apollo316** [comment]
Seconded! And thank you for this amazing plugin! So excited to see support for the tuya devices continuing. Turns out this works with some of the Amazon garage door openers and I picked up a $30 one with wired door sensor as I was tired of the battery-operated Insignia and the Chaimberlain (POS!!) before that. I couldn't be happier right now! 

I can confirm that this [rando one](https://www.amazon.com/gp/product/B086MKP14K) works when set manually as a Switch in the plugin. It would just be cool to pick a device type of Garage Door Opener so commands are more accurate (e.g. turn on the garage door = awkward vs. open the garage door) and would also then use the Homekit security protocol of not allowing it to be opened without unlocking the phone. Personally, I'm not a fan of not having a choice whether my phone has to be unlocked or not for the garage door to open (closes without need for security) and would rather be able to open the door without unlocking the phone. But, it is what it is if the plugin can't change the nature of Homekit's security. Simply choosing Garage Door type would be fantastic though.

P.S.
I'm happy to be a tester for you if you'd like. It looks like there are characteristics it can read for the opener I'm just not sure how to see what they are.

**Comment by imtitanic** [comment]
> Could you please follow the steps outlined in ["How to check whether the API this library uses can control your device?"](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device).

Maybe is too late to this but... Hahaha

```
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [{   'data': {'online': True, 'state': False},
                                      'dev_type': 'switch',
                                      'ha_type': 'switch',
                                      'icon': 'https://images.tuyaus.com/smart/icon/ay1537847617560vAgbw/1566982841d9f5a935d5c.png',
                                      'id': '77010881483fda436772',
                                      'name': 'Garage Door'}],
                   'scenes': []}}
```
