### ISSUE TITLE
Window cover

### ISSUE THREAD

**Issue by Stetocasa** [milo526/homebridge-tuya-web#453]
Every time that homebridge restar show the status of the curtain as closed.
If possible to push the real status of the curtain from Tuya or at max insert the possibility to define the standard mode (not closed but open)
Thanks

**Comment by Stetocasa** [comment]
@milo526 any feedback please?

**Comment by juan2three** [comment]
x2 Window Covers (shades) always do not have a proper indicator whether is open or closed. Also it always says "50% Open" whether is fully opened or fully closed. Another issue is when you hold down the device, a sliding bar appears to set the height for the covers but the only valid options are all the way down (0%) or all the way up (100%). This is not intended behavior since the Tuya app has the sliding method working for any percentage
