### ISSUE TITLE
All devices show as both switch and outlet

### ISSUE THREAD

**Issue by vascott1** [milo526/homebridge-tuya-web#60]
Seems that all of my switches/outlets are showing up now as both a switch and an outlet. The switches are still working even though the "outlet" version does nothing.  The one double outlet I have seems to have stopped working with with either one. Most odd. Be happy to supply whatever mighty be needed.

**Comment by milo526** [comment]
Please clear your homebridge device cache.

**Comment by brianhackel** [comment]
Same issue as of update today. Clearing cache didn't help. One switch, one outlet per plug, only the "switch" seems to have any effect.

**Comment by brianhackel** [comment]
Had to uninstall/reinstall plugin and reconfigure with a homebridge reboot in between. Appears to be back to normal (1 device per outlet).

**Comment by vascott1** [comment]
Brian. Can you elaborate on reconfigure?
  

  
  

  
  
>

**Comment by brianhackel** [comment]
> Brian. Can you elaborate on reconfigure?
> […](#)

Has part of the plugin uninstallation, I had it delete the configuration. I removed the Tuya references from the cachedAccessories file and restarted Homebridge. Then i reinstalled the plugin and re-added the configuration details (username, password and platform). After another Homebridge restart, i got only one switch per device as before.

**Comment by vascott1** [comment]
Ah. Got it. Will give it a shot. Thanks
  

  
  

  
  
>

**Comment by vascott1** [comment]
Success. Thanks Brian

**Comment by milo526** [comment]
> > Brian. Can you elaborate on reconfigure?
> 
> > […](#)
> 
> 
> 
> As part of the plugin uninstallation, I had it delete the configuration. I removed the Tuya references from the cachedAccessories file and restarted Homebridge. Then i reinstalled the plugin and re-added the configuration details (username, password and platform). After another Homebridge restart, i got only one switch per device as before.

It is almost as if you cleared your homebridge device cache 🙈

Glad it now worked!
If this issue is solved, can you please close it

**Comment by brianhackel** [comment]
> > > Brian. Can you elaborate on reconfigure?
> > 
> > > […](#)
> > 
> > 
> > 
> > As part of the plugin uninstallation, I had it delete the configuration. I removed the Tuya references from the cachedAccessories file and restarted Homebridge. Then i reinstalled the plugin and re-added the configuration details (username, password and platform). After another Homebridge restart, i got only one switch per device as before.
> 
> It is almost as if you cleared your homebridge device cache 🙈
> 
> Glad it now worked!
> If this issue is solved, can you please close it

I don't suppose we really need the sarcasm. I cleared the cache and obtained no joy until I completely uninstalled the plugin and flushed its configuration completely.

**Comment by milo526** [comment]
Clearing the device cache from file will require a restart before it takes effect, a majority of the users of this plugin use config-ui-x if you clear your cache through there it does the automatic restart or at least cache reload.

**Comment by mbierman** [comment]
I noticed that clearing the cache of the device does mean that only one device shows. However, even after restarting homebridge it took a while for the remaining copy of the device to start responding even well after homebridge resumed.

I know this is a minor annoyance, but because 0.5.4 has been giving me some issues, I have reverted back to 0.3.3 for now. Each time I up or downgrade, I get the duplicate devices and have to clear them, restart homebridge, and update any scenes and rules that use the devices. I'm not sure why 0.3.3 and 0.4.5 create different tuya device types. It wouldn't be such a big deal if it was a one time upgrade issue but since I have bounced back and forth between versions in the last week this is unfortunate.

**Comment by milo526** [comment]
@mbierman i understand, v4.5 is more compliant with HomeKit specification, v3.3 had an issue there. It still worked but it wasn't supposed to (I used the active state for outlets instead of the on state).

Hopefully v4.5 will soon be stabilized.

**Comment by sterumbelow** [comment]
Hi, @milo526. 

I commented about this in the other thread where you offered 0.4.7 per-release. 

Rather than clearing caches and having to reset all scenes, accessories and automations, you can change the setting in home to ‘show as separate tiles’ and then go back in and group them together, so they function as one. 

It’s a workaround but works perfectly and saves you having to reset your entire Home configuration. 

Will a future update (or 0.4.7 official) fix the issue with accessories showing as two items? I’m sure most people won’t want to reset caches! (Not even sure how to do that on Hoobs!). 

Thanks very much,
Ste.

**Comment by mbierman** [comment]
@sterumbelow That does not work as far as I can tell. I don't know of a way to join to separate devices as one. 

Since this is a one time transition which is more homekit compliant, it isn't unreasonable to migrate the rules and scenes one time.

**Comment by sterumbelow** [comment]
> @sterumbelow That does not work as far as I can tell. I don't know of a way to join to separate devices as one. 
> 
> 
> 
> Since this is a one time transition which is more homekit compliant, it isn't unreasonable to migrate the rules and scenes one time. 

It does work because I've done it! ![image](https://user-images.githubusercontent.com/68124742/90719780-2b2fe480-e2ad-11ea-8472-e61c0b9accf1.jpeg)

![image](https://user-images.githubusercontent.com/68124742/90719808-36831000-e2ad-11ea-9a91-cc6471a85297.jpeg)

![image](https://user-images.githubusercontent.com/68124742/90719790-3125c580-e2ad-11ea-8482-cd922cef5cf6.png)

**Comment by mbierman** [comment]
@sterumbelow Ah, I see ungroup and then regroup them. I'm surprised that works, but o.k.!

**Comment by bwp91** [comment]
the name of your device intrigues me! 🧐

**Comment by milo526** [comment]
This work-around seems to be a better solution fixing it on the plugin side.
Due too different setups and configurations it has been proven hard to properly fix this on the plugin side, any fix I tried could result in data-loss. I'd rather people do the work-around when they are ready and can keep control of their automations.
