### ISSUE TITLE
[Feature Request] Ignore Particular Virtual IDs

### ISSUE THREAD

**Issue by walshy1009** [milo526/homebridge-tuya-web#62]
**Is your feature request related to a problem? Please describe.**
Somewhat. Using Tuya Web & Tuya Lan in homebridge as some devices work in one but not in the other.

**Describe the solution you'd like**
A black/ignore list that can be set in the config of particular virtual IDs so that the plugin can ignore those IDs so they don't come up in HomeKit at all.

E.G.: I have a globe that works better with TuyaLan but TuyaWeb recognises it too so they both show up in HomeKit. This way I can tell TuyaWeb to ignore the virtual ID of that bulb so the duplicate isn't an issue in the Home app.

**Comment by milo526** [comment]
Seems like a good idea and like something that shouldn't be to hard!

While it is not my highest priority, I expect to work on this soon.

**Comment by milo526** [comment]
Could you see if installing [`v0.4.7-1`](https://www.npmjs.com/package/@milo526/homebridge-tuya-web) gives you the desired result? This is tagged under the `@next` branch.

You can use the following command, it might need some alterations, since this is a pre-release; you will not be able to upgrade trough config-ui-x.
`npm i @milo526/homebridge-tuya-web@0.4.7-1`

**Comment by milo526** [comment]
This issue is solved in [v0.4.7](http://github.com/milo526/homebridge-tuya-web/releases/tag/v0.4.7)

If you have any other issues or are still experiencing the issue documented here, please open a new issue.


If you use this plugin heavily please consider [becoming a sponsor](https://github.com/sponsors/milo526) or [making a one time donation](https://bunq.me/HomebridgeTuyaWeb)
