### ISSUE TITLE
Tuya Web setup not consistent and interval timing is set to 350

### ISSUE THREAD

**Issue by donjalex2** [milo526/homebridge-tuya-web#67]
<img width="1159" alt="Screen Shot 2020-08-22 at 4 38 58 PM" src="https://user-images.githubusercontent.com/70077629/90966987-2417fa80-e496-11ea-86e4-b7e9ff3166f1.png">
**Describe the bug**

*On the Tuya Web setup it works for a little bit and then everything becomes unresponsive.
On the Tuya Lan setup, again everything works and then I get the following messages:
Tuya Lan setup went well for an hour, then I start to get this on from some of my devices within Hoobs:
[TuyaAccessory] Socket had a problem and will reconnect to Island 2 (EHOSTUNREACH)
[TuyaAccessory] Slowing down retry attempts; if you see this happening often, it could mean some sort of incompatibility.
Don't understand... I've spent the last couple nights trying to figure this out and notta... Any help is appreciated.

**Comment by milo526** [comment]
This issue is solved in [v0.4.7](http://github.com/milo526/homebridge-tuya-web/releases/tag/v0.4.7)

If you have any other issues or are still experiencing the issue documented here, please open a new issue.

If you use this plugin heavily please consider [becoming a sponsor](https://github.com/sponsors/milo526) or [making a one time donation](https://bunq.me/HomebridgeTuyaWeb)
