### ISSUE TITLE
Relay not present in "devices"

### ISSUE THREAD

**Issue by Skyman81** [milo526/homebridge-tuya-web#84]
I installed a RELAY compatible with TUYA: LORATAP/QCSMART (the ones with wifi and IR).
The relay work with tuya app but not present into HB and HK.

In the log is reported this:
![714A10A8-2B7F-4B18-B58E-D1562C7A2996](https://user-images.githubusercontent.com/71496894/93588765-2a719780-f9ac-11ea-82df-c48139f04ea9.jpeg)

PS: just checked more times the SN is correct. I also try to set the name of the device instead the SN but same problem (it's not valid).

there is another item connected to TUYA account and is working good so the problem maybe is this relay (updated to last fm 1.1.2)

![A4E8D385-618D-4940-A6BE-B608DAEBA7CC](https://user-images.githubusercontent.com/71496894/93611192-46863080-f9ce-11ea-9776-1bfe00182eee.jpeg)

This is the device:
![A006A79C-9FFB-4493-8647-98D08C1C0A80](https://user-images.githubusercontent.com/71496894/93620808-e0ec7100-f9da-11ea-8377-69379a3dff4d.jpeg)

**Comment by milo526** [comment]
Please post the the config here (as text instead of the screenshot you already posted)
Furthermore also post the result of [the steps under How to check whether the api this library uses can control your device.](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device).

If you can provide me with these 2 pieces of information I can try to help you.

**Comment by Skyman81** [comment]
Now i will post the config... in the next days o will try to post the other things:
![Uploading 591F6FDF-A312-488B-9680-CF6C4620E361.jpeg…]()

**Comment by milo526** [comment]
@Skyman81 I deleted your comment as the marker is not a proper redaction tool and anybody with access to that picture could read your password. Please consider resetting your tuya password.

As requested please provide the configuration as text instead of as an image. This makes my debugging process a whole lot easier. As you request my assistant it would be nice for you to do that what you can do to make my debugging process easier 😉
