### ISSUE TITLE
Connexion Tuya

### ISSUE THREAD

**Issue by Birdyfive13500** [milo526/homebridge-tuya-web#88]
Hello, I just set up a homebridge from a raspberry pi 3.

I added a certified tuya plugin but when I add my username and my platform at startup I get an error message.

TuyaWebPlatform] Authentication error: Get accesstoken failed. Username or password error!

But my IDs are right
I use Smart life

**Comment by milo526** [comment]
Hello,

You just skipped 99% of the issue template, please know that I am just a student working on this in my own time. I do not get paid to do this. I am not affiliated with tuya or smartlife.

It is frustrating for me to get this kind of issue where you just expect me to do a lot of work to help you while you failed to follow the issue template, where you didn't want to put any effort in providing me with even the most basic information.

**Comment by milo526** [comment]
You are probably using sign-in with Apple and/or Google.

Sign-in with apple(or google) is not supported and will not be supported due to limitations imposed by tuya and/or apple.
This is not something I can easily work around.

There are some other users who have had this problem before and they have had varying levels of success. You can[ read what they did here](https://github.com/milo526/homebridge-tuya-web/issues/31).

**Comment by duritsyn** [comment]
Thanks for this thread! 
As an additional note: there is possibility to remove and reset  accessories from app. Also to remove existing account.
I used 10 min mail to create new. Now everything works perfectly. Spend additional 3 min to do this.
